java_test(
    name = "IdwallFormatterTest",
    srcs = ["idwall/desafio/string/IdwallFormatterTest.java"],
    test_class = "idwall.desafio.string.IdwallFormatterTest",
    deps = ["//src/main/java:string-formatter"]
)

java_test(
    name = "LimitedTextLineTest",
    srcs = ["idwall/desafio/string/LimitedTextLineTest.java"],
    test_class = "idwall.desafio.string.LimitedTextLineTest",
    deps = ["//src/main/java:string-formatter"]
)