proto_library(
    name = "reddit_crawler_proto",
    srcs = ["reddit-crawler.proto"]
)

java_proto_library(
    name = "reddit_crawler_java_proto",
    deps = [":reddit_crawler_proto"],
    visibility = ["//visibility:public"]
)